{% set name = "kotlin-language-server" %}
{% set version = "1.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fwcd/kotlin-language-server/archive/{{ version }}.tar.gz
  sha256: 4cb346f989ef114f6073cb9401968a7dd27eb5cd96993fa6856203610a13f96e

build:
  noarch: generic
  number: 0

requirements:
  build:
    - maven
    - openjdk =21
    - sed
  run:
    - openjdk

test:
  commands:
    - kotlin-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/fwcd/kotlin-language-server
  license: MIT
  license_file:
    - LICENSE.txt
    - build/reports/dependency-license/
  summary: Kotlin code completion, diagnostics and more for any editor/IDE using the Language Server Protocol
  dev_url: https://github.com/fwcd/kotlin-language-server

extra:
  recipe-maintainers:
    - danielnachun
